/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/nameText.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={nodes.Text.material} geometry={nodes.Text.geometry} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        material={nodes.Text001.material}
        geometry={nodes.Text001.geometry}
        position={[0.6, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text002.material}
        geometry={nodes.Text002.geometry}
        position={[1.3, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text003.material}
        geometry={nodes.Text003.geometry}
        position={[1.9, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text004.material}
        geometry={nodes.Text004.geometry}
        position={[2.9, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text005.material}
        geometry={nodes.Text005.geometry}
        position={[3.3, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text006.material}
        geometry={nodes.Text006.geometry}
        position={[3.9, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text007.material}
        geometry={nodes.Text007.geometry}
        position={[4.5, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text008.material}
        geometry={nodes.Text008.geometry}
        position={[4.9, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text009.material}
        geometry={nodes.Text009.geometry}
        position={[5.6, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text010.material}
        geometry={nodes.Text010.geometry}
        position={[6.3, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={nodes.Text011.material}
        geometry={nodes.Text011.geometry}
        position={[6.8, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}
